source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sinatra'
gem 'camping'
gem 'ramaze'

gem 'unicorn'

gem 'sqlite3'
gem 'sequel'

gem 'do_sqlite3'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-transactions'
gem 'dm-sqlite-adapter'
